version: '3.8'

services:
  mongodb:
    image: mongo:6.0.17
    container_name: friday_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: friday_mongo_password
      MONGO_INITDB_DATABASE: friday
    volumes:
      - ./storage/data/mongodb:/data/db
      - ./storage/data/mongodb/configdb:/data/configdb
    networks:
      - friday_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: ["mongod", "--bind_ip_all"]

  redis:
    image: redis:7.2.5-alpine
    container_name: friday_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./storage/data/redis:/data
    networks:
      - friday_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

networks:
  friday_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
